# Generated by Django 3.2.4 on 2021-06-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=2000, null=True)),
                ('room_max_students', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=1000, null=True)),
                ('subject_number_of_students', models.IntegerField(null=True)),
                ('subject_groups', models.IntegerField(null=True)),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=2000, null=True)),
                ('speciality_subjects', models.ManyToManyField(to='timetableCSP.Subject')),
            ],
        ),
    ]
