# Generated by Django 3.2.4 on 2021-06-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0002_auto_20210617_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='speciality_subjects',
            new_name='subjects',
        ),
    ]
