# Generated by Django 3.2.4 on 2021-06-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0006_auto_20210618_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('timetable_name', models.CharField(max_length=2000, null=True)),
                ('date_creation', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(null=True)),
                ('timeSlot', models.CharField(choices=[('08:30 - 09:50', '08:30 - 09:50'), ('10:00 - 11:20', '10:00 - 11:20'), ('11:40 - 13:00', '11:40 - 13:00'), ('13:30 - 14:50', '13:30 - 14:50'), ('15:00 - 16:20', '15:00 - 16:20'), ('16:30 - 17:50', '16:30 - 17:50')], max_length=2000, null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=2000, null=True)),
                ('type_of_class', models.CharField(max_length=2000, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.room')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.speciality')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.teacher')),
            ],
        ),
    ]
