# Generated by Django 3.2.4 on 2021-06-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0007_class_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetableCSP.timetable'),
        ),
    ]
