# Generated by Django 3.2.4 on 2021-06-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0008_class_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
