# Generated by Django 3.2.4 on 2021-06-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0009_alter_timetable_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='map_key',
            field=models.IntegerField(null=True),
        ),
    ]
