# Generated by Django 3.2.4 on 2021-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0010_class_map_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('freetime_id', models.AutoField(primary_key=True, serialize=False)),
                ('domaines', models.CharField(choices=[('Monday,08:30 - 09:50', 'Monday,08:30 - 09:50'), ('Monday,10:00 - 11:20', 'Monday,10:00 - 11:20'), ('Monday,11:40 - 13:00', 'Monday,11:40 - 13:00'), ('Monday,13:30 - 14:50', 'Monday,13:30 - 14:50'), ('Monday,15:00 - 16:20', 'Monday,15:00 - 16:20'), ('Monday,16:30 - 17:50', 'Monday,16:30 - 17:50'), ('Tuesday,08:30 - 09:50', 'Tuesday,08:30 - 09:50'), ('Tuesday,10:00 - 11:20', 'Tuesday,10:00 - 11:20'), ('Tuesday,11:40 - 13:00', 'Tuesday,11:40 - 13:00'), ('Tuesday,13:30 - 14:50', 'Tuesday,13:30 - 14:50'), ('Tuesday,15:00 - 16:20', 'Tuesday,15:00 - 16:20'), ('Tuesday,16:30 - 17:50', 'Tuesday,16:30 - 17:50'), ('Wednesday,08:30 - 09:50', 'Wednesday,08:30 - 09:50'), ('Wednesday,10:00 - 11:20', 'Wednesday,10:00 - 11:20'), ('Wednesday,11:40 - 13:00', 'Wednesday,11:40 - 13:00'), ('Wednesday,13:30 - 14:50', 'Wednesday,13:30 - 14:50'), ('Wednesday,15:00 - 16:20', 'Wednesday,15:00 - 16:20'), ('Wednesday,16:30 - 17:50', 'Wednesday,16:30 - 17:50'), ('Thursday,08:30 - 09:50', 'Thursday,08:30 - 09:50'), ('Thursday,10:00 - 11:20', 'Thursday,10:00 - 11:20'), ('Thursday,11:40 - 13:00', 'Thursday,11:40 - 13:00'), ('Thursday,13:30 - 14:50', 'Thursday,13:30 - 14:50'), ('Thursday,15:00 - 16:20', 'Thursday,15:00 - 16:20'), ('Thursday,16:30 - 17:50', 'Thursday,16:30 - 17:50'), ('Friday,08:30 - 09:50', 'Friday,08:30 - 09:50'), ('Friday,10:00 - 11:20', 'Friday,10:00 - 11:20'), ('Friday,11:40 - 13:00', 'Friday,11:40 - 13:00'), ('Friday,13:30 - 14:50', 'Friday,13:30 - 14:50'), ('Friday,15:00 - 16:20', 'Friday,15:00 - 16:20'), ('Friday,16:30 - 17:50', 'Friday,16:30 - 17:50')], max_length=2000, null=True)),
            ],
        ),
    ]
