# Generated by Django 3.2.4 on 2021-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0011_freetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetime',
            old_name='domaines',
            new_name='domaine',
        ),
        migrations.AddField(
            model_name='teacher',
            name='freetimes',
            field=models.ManyToManyField(null=True, to='timetableCSP.FreeTime'),
        ),
    ]
