# Generated by Django 3.2.4 on 2021-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableCSP', '0012_auto_20210622_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetime',
            name='freetime_key',
            field=models.IntegerField(null=True),
        ),
    ]
